### ISSUE TITLE
High CPU Utilization

### ISSUE THREAD

**Issue by spencerlievens** [duality-solutions/Sequence#13]
### Describe the issue
CPU usage is high, ranging from 60-100% of 1 x vCPU.  This occurs after a full chain sync and with an empty wallet.
### Expected behavior
CPU while the wallet is idle should be under 2%.  My experience is it uses onder 1%.
### Screenshots
![High CPU](http://i.imgur.com/6nAuZAP.png)
### What platform are you using (Linux, Windows, Mac)
Linux Ubuntu 16.04 64-bit.with

**Comment by quantumgravity444** [comment]
Again, this is because the DNS seeders are throwing themselves in an infinite self referantial loop when they refer to themselves as the seed of themselves. Haha reminds me of Godel's Proof. 

An easy and short term fix would to just add hard coded seed nodes and scrap the faulty DNS seeders (Sorry Dennis) and the other unreachable ones that I put up. 

Then we need to do a quck and dirty fork of a Go codebase and use the Go seeder that can seed both silk and darksilk on it's own.

**Comment by quantumgravity444** [comment]
But for users to remove this problem, simply delete your peers.dat and add some addnodes to your silk.conf file in the data directory. Fixed it for me right away.

**Comment by beralt85** [comment]
Deleting peers.dat (with silkd stopped) helped initially, but immediately after the full sync it went up again and peers.dat was recreated. (>100% according to top on RPi3).
Shall I delete peers.dat while the server is running?

Or do you mean ddns.dat?

**Comment by SCDeveloper** [comment]
Have I now resolved this with the v1.2.0.0 branch?

**Comment by SCDeveloper** [comment]
Resolved in v1.2.0.0
